### ISSUE TITLE
SOAPpy.Errors.HTTPError: <HTTPError -1 Empty response from server

### ISSUE THREAD

**Issue by datonli** [jeffkit/SOAPpy#6]
SOAPpy.Errors.HTTPError: <HTTPError -1 Empty response from server
after I run the hello code just like you give

**Comment by datonli** [comment]
Traceback (most recent call last):
  File "soap_cli.py", line 3, in <module>
    print server.hello()
  File "build/bdist.macosx-10.6-intel/egg/SOAPpy/Client.py", line 547, in **call**
  File "build/bdist.macosx-10.6-intel/egg/SOAPpy/Client.py", line 569, in __r_call
  File "build/bdist.macosx-10.6-intel/egg/SOAPpy/Client.py", line 432, in __call
  File "build/bdist.macosx-10.6-intel/egg/SOAPpy/Client.py", line 288, in call
SOAPpy.Errors.HTTPError: <HTTPError -1 Empty response from server
Code: ''
Headers: None>
